### ISSUE TITLE
Relationship between this repo and the ncISO in the Unidata thredds repo?

### ISSUE THREAD

**Issue by rsignell-usgs** [ethanrd/threddsIso#1]
What is the relationship between this ncISO repo and the ncISO stuff in the Unidata thredds repo at https://github.com/Unidata/thredds ?

**Comment by shane-axiom** [comment]
As @rsignell-usgs [suggested](https://github.com/ethanrd/threddsIso/issues/2#issuecomment-54648798), it's confusing to have issues managed on this repo while development/pull requests are happening on the fork.

**Comment by rsignell-usgs** [comment]
@ethanrd, to fix this, perhaps you could:
* update this repo from https://github.com/Unidata/threddsIso to bring your version up to date
* delete the one on unidata
* transfer ownership of this one to unidata

**Comment by ethanrd** [comment]
@rsignell-usgs - Sorry this took so long.

I made a request to GitHub that they detach the Unidata/threddsIso repo from this one so it could be standalone. (GitHub support had it done in less than an hour.) I've marked this one as deprecated in the README and with this I've closed/moved all open issues.

May delete the repo at some point in the not too distant future (?).
