### ISSUE TITLE
Update NcISO to specify gmd:protocol for service endpoints

### ISSUE THREAD

**Issue by rsignell-usgs** [ethanrd/threddsIso#2]
As discussed in the pycsw issue here: https://github.com/geopython/pycsw/issues/269, catalog services that rely on OWSlib like pycsw expect to have `gmd:protocol` specified in order to populate the `scheme` in the `references` that get returned from a CSW request.  Without this, SOS, WMS, OpeNDAP endpoints, etc always come back with `scheme` of `None`.

Should just need to modify the `UnidataDD2MI.xsl` file:
https://github.com/ethanrd/threddsIso/blob/34a9e4bd0676bb095a3c6f4ca89def52cdf90034/src/main/resources/xsl/nciso/UnidataDD2MI.xsl

@pacioos, I know you've addressed this -- can you please submit a PR to fix this?

**Comment by shane-axiom** [comment]
Just a note that it's a bit confusing to be collecting issues on this repo and submitting pull requests to the fork, i.e. +1 for https://github.com/ethanrd/threddsIso/issues/2#issuecomment-54648798

**Comment by ethanrd** [comment]
As a PR for this issue has been made and merged on the Unidata/threddsIso repo (https://github.com/Unidata/threddsIso/pull/1), I am closing this issue.
