### ISSUE TITLE
Command line ncISO code?

### ISSUE THREAD

**Issue by shane-axiom** [ethanrd/threddsIso#4]
This may not apply, but is there any connection between this repo and the command line version of ncISO? The line between ncISO and threddsISO seems to be a little hazy. TDS documentation and configuration usually references the embedded ncISO plugin, but according to this [NGDC page](http://www.ngdc.noaa.gov/eds/tds/) and this repository name ncISO is actually a jar meant for command line execution against a remote TDS instance, and threddsISO is the name of the TDS embedded plugin.

In any case, the CLI ncISO version on NGDC's page is broken, and I haven't had luck getting on their mailing list. Any traction/illumination here? A brief README might make the relation of this repo to ncISIO apparent.

**Comment by ethanrd** [comment]
@shane-axiom - I'm closing this issue here and have moved it to the Unidata/threddsIso repo (https://github.com/Unidata/threddsIso/issues/7) which is the repo now used to build threddsIso for the THREDDS Data Server (TDS - https://github.com/Unidata/thredds) distribution.
